BASE_URL_IDX = 'https://testerc20univ.indexer-test.gateway.fm/'


endpoints = [
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersArrayStructEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBoolArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBoolEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBoolIndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBoolSliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesIndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesSizesArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesSizesEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesSizesIndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesSizesSliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersBytesSliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersEnumArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersEnumEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersEnumIndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersEnumSliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntGroup1IndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntGroup1SliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntGroup2IndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntGroup2SliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntGroup3IndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersIntGroup3SliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersNestedStructEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersSimpleStructEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersSliceStructEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersStringArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersStringEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersStringIndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersStringSliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntArrayEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntGroup1IndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntGroup1SliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntGroup2IndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntGroup2SliceEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntGroup3IndexedEvents",
    f"{BASE_URL_IDX}api/v1/events/GetByFiltersUIntGroup3SliceEvents"
]

